// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emlfilegeneration.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the EMLFileGeneration module
	public static void aCT_CreateEditAttachment(IContext context, emlfilegeneration.proxies.Attachment _attachment, emlfilegeneration.proxies.Email _email)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Attachment", _attachment == null ? null : _attachment.getMendixObject());
		params.put("Email", _email == null ? null : _email.getMendixObject());
		Core.microflowCall("EMLFileGeneration.ACT_CreateEditAttachment").withParams(params).execute(context);
	}
	public static void aCT_EmailConfiguration_Save(IContext context, emlfilegeneration.proxies.EmailConfiguration _emailConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailConfiguration", _emailConfiguration == null ? null : _emailConfiguration.getMendixObject());
		Core.microflowCall("EMLFileGeneration.ACT_EmailConfiguration_Save").withParams(params).execute(context);
	}
	public static void aCT_GenerateEMLFile(IContext context, emlfilegeneration.proxies.Email _email)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Email", _email == null ? null : _email.getMendixObject());
		Core.microflowCall("EMLFileGeneration.ACT_GenerateEMLFile").withParams(params).execute(context);
	}
	public static java.lang.String aCT_GetBearerToken_ForAPI(IContext context, emlfilegeneration.proxies.EmailConfiguration _emailConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailConfiguration", _emailConfiguration == null ? null : _emailConfiguration.getMendixObject());
		return (java.lang.String) Core.microflowCall("EMLFileGeneration.ACT_GetBearerToken_ForAPI").withParams(params).execute(context);
	}
	public static void aCT_GetEMLFile(IContext context, emlfilegeneration.proxies.GenerateEML_Graph _generateEML_Graph)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GenerateEML_Graph", _generateEML_Graph == null ? null : _generateEML_Graph.getMendixObject());
		Core.microflowCall("EMLFileGeneration.ACT_GetEMLFile").withParams(params).execute(context);
	}
	public static java.lang.String aCT_GetEMLFileFromGraph(IContext context, java.lang.String _messageID, java.lang.String _email, java.lang.String _accessToken)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MessageID", _messageID);
		params.put("Email", _email);
		params.put("AccessToken", _accessToken);
		return (java.lang.String) Core.microflowCall("EMLFileGeneration.ACT_GetEMLFileFromGraph").withParams(params).execute(context);
	}
	public static emlfilegeneration.proxies.EmailConfiguration dS_EmailConfiguration(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("EMLFileGeneration.DS_EmailConfiguration").withParams(params).execute(context);
		return result == null ? null : emlfilegeneration.proxies.EmailConfiguration.initialize(context, result);
	}
	public static java.lang.String sUB_GetEMLFileContent(IContext context, emlfilegeneration.proxies.EmailConfiguration _emailConfiguration, java.lang.String _messageID, java.lang.String _email)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailConfiguration", _emailConfiguration == null ? null : _emailConfiguration.getMendixObject());
		params.put("MessageID", _messageID);
		params.put("Email", _email);
		return (java.lang.String) Core.microflowCall("EMLFileGeneration.SUB_GetEMLFileContent").withParams(params).execute(context);
	}
}
